### PR TITLE
Replace pdflib with pdfminersix (text) & pikpedf (images)

### PR DESCRIPTION
**Pull request by stchris**
Things happening in this PR:

- we stop using pdflib
- ingestors/documents/pdf.py no longer knows about PDF handling, instead ingestors/support/pdf.py deals with PDF libs (before these two used to share the responsibility which made it very hard to keep track of state and switch to a different PDF library)
- ingestors/support/pdf.py introduces two dataclasses: the `PdfModel` represents a pdf document and the `PdfPageModel` a page within the pdf document. These are used to pass data back after parsing to the `extract_*` methods (which create FTM entities out of that data). This decouples the pdf parsing implementation from our interpretation of it
- added a unit test to make sure that we handle password protected PDFs (in that: we create an entity and record the failed state of it)
- added additional info logging to state that we hit a password protected PDF

Open tasks:
- [x] check timestamp of converted documents, make sure to avoid parsing the metadata of newly converted pdfs instead of the original document (see https://github.com/alephdata/ingest-file/pull/380#issuecomment-1327559588)
- [x] test that JBIG2 support is there

### CODE REVIEW

**Comment by pudo** [comment]
Maybe for "historical context": I think one of the reasons for splitting up the parsing between the two modules was to avoid parsing the metadata of PDFs we'd just created via convert-document. If we do that, we might end up with a scenario where all the word documents are "created at" "5 seconds ago" because that's when we turned their word form into a PDF... 

This looks reasonable overall. I'm curious about the perf impact of using pdfminer.six, and whether this will be able to handle JBIG2 images. The Image-finding code is super funky, love it :)

**Comment by stchris** [comment]
> Maybe for "historical context": I think one of the reasons for splitting up the parsing between the two modules was to avoid parsing the metadata of PDFs we'd just created via convert-document. If we do that, we might end up with a scenario where all the word documents are "created at" "5 seconds ago" because that's when we turned their word form into a PDF...

Ah thanks, that's good to know. I will have to look into that.

> This looks reasonable overall. I'm curious about the perf impact of using pdfminer.six

Me too :) Overall from the benchmarks I've seen and the ones I've done I'm surprised to say that we are actually gaining speed, considering we are using 2 pdf libs serially.

> and whether this will be able to handle JBIG2 images. The Image-finding code is super funky, love it :)

Another good point, thank you. Will add a test for this!

**Comment by stchris** [comment]
So JBIG2 support is there, it was a reason to pick `pikepdf`. The OCR result is decent, missing a character here and there, but that's slightly out of scope here. I did add some test coverage for that though.

**Comment by pudo** [comment]
Hella impressive! And I can finally come play with my M1 again! :)

**Comment by stchris** [comment]
> we might end up with a scenario where all the word documents are "created at" "5 seconds ago" because that's when we turned their word form into a PDF...

@pudo I added a test to check that and the authored_at / modified_at timestamps seem ok to me. Unless I'm doing something wrong? Can you check if I'm missing something there?

**Pull request merged**
