### PR TITLE
Add Khmer tesseract OCR package

### PR DESCRIPTION
**Pull request by arky**
Add Khmer 'khm' language injestion support using tesseract package.

https://github.com/alephdata/aleph/issues/1986

### CODE REVIEW

**Review by sunu — APPROVED** [review]

**Comment by arky** [comment]
Thanks for the merge @sunu I'll do some additional testing on dev branch.

Could you tell us when this would be available for public via the official Aleph platform? I would like native Khmer speakers to start using this feature widely. Thanks!

**Comment by sunu** [comment]
Hi @arky, we are planning to deploy the latest changes to OCCRP's Aleph within the next couple of days. I will ping you to let you know when Khmer language support is live.

**Comment by arky** [comment]
Thank you @sunu Much appreciated.

**Comment by sunu** [comment]
Hi @arky! Unfortunately we couldn't do a deployment last week. We are still waiting on a few things before we can do that. But hopefully we can get it live by the end of this week.

**Comment by arky** [comment]
No worries Thanks for keeping me posted @sunu

**Comment by sunu** [comment]
Hi @arky, Khmer language support for OCR should be available on OCCRP's Aleph now! Let me know whether it's working or not.

It's still not packaged into a Aleph release. But that will probably happen only after the holidays.

**Pull request merged**
